apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - platform-source.yaml
  - platform-vars.yaml
  - modules/core.yaml
  - modules/mesh.yaml
  - modules/certs.yaml
  - modules/auth.yaml
  - modules/monitoring.yaml
  - modules/tracing.yaml
  - modules/autoscaling.yaml
  - modules/dashboard.yaml
  # Add app GitRepository + Kustomization files here
  # - apps/
